### ISSUE TITLE
O arquivo mapFeatures.js está vazio

### ISSUE THREAD

**Issue by SOS3DCOVID19** [franklinveras/SOS-3D-Logistica#1]
Não sei se isso faz diferença em rodar a app, porém esse arquivo está vazio. Além disso, não estou conseguindo rodar o mapa com os hospitais (aquele com os marcadores vermelho e amarelo).

**Comment by franklinveras** [comment]
este arquivo foi criado com o intuito de colocar botões de navegação e toggle de camadas, mas nunca chegou a ser implementado. Logo ele realmente é vazio. Vou remover o arquivo para não gerar dúvidas.

**Comment by franklinveras** [comment]
Arquivo mapFeatures.js removido: 75a10ce
